adminUserName:  Admin
adminPassword:  Admin
userNotRegisteredMsg: You are not a registered User. Register to login.
adminErrorMsg:  Contact Admin Service.
userPasswordOrIdIncorrectMsg: User ID or Password is incorrect. Plese try agin.